version: "3"

services:

  gateway:
    image: openresty/openresty:alpine
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gateway/filter.lua:/etc/nginx/filter.lua
    env_file:
      - .env
    depends_on:
      - botengine
      - redis

  botengine:
    build: ./botengine
    env_file:
      - .env

  redis:
    image: redis:7-alpine