services:

  gateway:
    image: openresty/openresty:alpine
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gateway/filter.lua:/etc/nginx/filter.lua
      - ./js:/etc/nginx/js   # 🔥 TAMBAH INI
    env_file:
      - .env
    depends_on:
      - botengine

  botengine:
    build: ./botengine
    env_file:
      - .env