server {

    listen 80;
    server_name _;

    location / {
        access_by_lua_file /etc/nginx/filter.lua;
    }

    location /fp.html {
        root /etc/nginx/js;
    }

    location /fp {
        proxy_pass http://botengine:8080;
    }

}