worker_processes auto;

events {
  worker_connections 10240;
}

http {

  lua_package_path "/etc/nginx/?.lua;;";

  server {

    listen 80;

    location / {
      access_by_lua_file /etc/nginx/filter.lua;
    }

    # 🔥 serve fingerprint page
    location /fp.html {
      root /etc/nginx/js;
    }

  }

}