worker_processes auto;

events {
  worker_connections 10240;
}

http {

  server {

    listen 80;
    server_name _;

    # route utama → Lua filter
    location / {
      access_by_lua_file /etc/nginx/filter.lua;
    }

    # serve fingerprint page
    location = /fp.html {
      root /etc/nginx/js;
      add_header Content-Type text/html;
    }

    # forward ke Go botengine
    location /fp {
      proxy_pass http://botengine:8080;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # Timeout handling
      proxy_connect_timeout 5s;
      proxy_send_timeout 5s;
      proxy_read_timeout 5s;

      # Error handling
      error_page 502 = @botengine_down;
    }

    location @botengine_down {
      return 503;
    }

  }

}
